spring.application.name=02-sb-datajpa-intro

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ch_labs_spring_01
spring.datasource.username=root
spring.datasource.password=manish

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
