spring.application.name=03-sb-mvc-jsp


spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/ch_labs_spring_01
spring.datasource.username=root
spring.datasource.password=manish

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update


# InternalResourceViewResolver related view "prefix" & "suffix"
# for converting logical view names to paths to view files:
spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp
